### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by murrellb** [MurrellGroup/CodonMolecularEvolution.jl#1]
- [x] Finish initial difFUBAR port
- [ ] Add in input data validation, sanitisation, etc
- [x] Replace PyPlot with Plots.jl
- [ ] Add in vanilla FUBAR implementation
- [ ] Think about how/whether to incorporate simulations. Separate branch? Separate repo, one per method?
- [ ] Add more codon model methods
